### ISSUE TITLE
trouble getting members list (e.g. to authorize them)

### ISSUE THREAD

**Issue by apagr** [LFlare/ZeroTierNC#2]
`root@router:~#` ./zerotier-nc.py -n xxx --member-list
Traceback (most recent call last):
  File "./zerotier-nc.py", line 388, in <module>
    main()
  File "./zerotier-nc.py", line 379, in main
    out = member_list(nwid=args.n)
  File "./zerotier-nc.py", line 285, in member_list
    new_ztids[ztid] = alias(nwid=nwid, ztid=ztid)
  File "./zerotier-nc.py", line 146, in alias
    return y["alias"]+":"+yy["alias"]
TypeError: Can't convert 'collections.defaultdict' object to str implicitly
root@router:~# 

how to reproduce: 

1. create network, --net-add
2. join created network with cli, 
3. so far - so good - -n <id> --member-list works, unauthorized clients printed out
4. -n <id> --member-auth -z <member id>, works, client authorized
5. -n <id> --member-list throws the exception above

python 3.4.2, 
os: 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

**Comment by LFlare** [comment]
That is odd, can you give me the full command you are using?

**Comment by apagr** [comment]
./zerotier-nc -n myNetworkId --member-list
It only works until I authorize first client. This error shows up after first client has been authorized with -n myNetworkId -z unauthorizedClientId --member-auth. 
I've provided info how to reproduce issue. It may be crude a bit.

**Comment by apagr** [comment]
ZeroTier version is 1.2.4
Debian is up-to-date Jessie. 
Python is 3.4.2

**Comment by LFlare** [comment]
Sorry for not replying to you early @apagr, was away at a competition. Please try the latest push, should resolve your errors.

**Comment by apagr** [comment]
IT WORKS :D thanks for great tool. I've checked all other tools available on github, and yours is just the best :) thanks again.
